services:

  user-manager-service:
    build: ../users-manager
    ports:
      - "8090:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      DATASOURCE_URL: "jdbc:mysql://user-db:3306/users_manager?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true"
      DATASOURCE_USERNAME: "root"
      DATASOURCE_PASSWORD: "root"
      ACCOUNT_MANAGER_BASE_URL:  "http://account-manager-service:8080/accounts"
    depends_on:
      - "kafka"
      - "user-db"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  user-db:
    image: mysql:8.0
    container_name: user-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./user-init-db:/docker-entrypoint-initdb.d:rw,z
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  account-manager-service:
    build: ../account-manager
    ports:
      - "8091:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      DATASOURCE_URL: "jdbc:mysql://account-db:3306/accounts_manager?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true"
      DATASOURCE_USERNAME: "root"
      DATASOURCE_PASSWORD: "root"
    depends_on:
      - "kafka"
      - "account-db"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  account-db:
    image: mysql:8.0
    container_name: account-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_account_data:/var/lib/mysql
      - ./account-init-db:/docker-entrypoint-initdb.d:rw,z
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
  
volumes:
  mysql_user_data:
  mysql_account_data: